// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.app.update.background.scheduling.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.media.peerconnection.mtransport_process", true);
user_pref("app.normandy.startupRolloutPrefs.network.process.enabled", true);
user_pref("app.normandy.user_id", "caa3fd32-2a92-4599-8e5d-f537d06f6eb6");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.lastInstalledTaskVersion", 2);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1635970126);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1635970099);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1635970098);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1635970156);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1635970096);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 117);
user_pref("browser.newtabpage.activity-stream.impressionId", "{22bf0fe6-d0e0-4e74-9e34-44f0657628eb}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1635970098);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1635970143230");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1635971918230");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1635970100450");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1635991700450");
user_pref("browser.search.region", "DE");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1635970097");
user_pref("browser.startup.homepage_override.buildID", "20210927210923");
user_pref("browser.startup.homepage_override.mstone", "93.0");
user_pref("browser.startup.lastColdStartupCheck", 1635970097);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1635970098961");
user_pref("distribution.iniFile.exists.appversion", "93.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "DE");
user_pref("dom.push.userAgentID", "4a7add9789324232845d13dbb3fdc7ad");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210927210923");
user_pref("extensions.lastAppVersion", "93.0");
user_pref("extensions.lastPlatformVersion", "93.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"493b063c-9723-44e7-8522-7ea43df4c580\",\"formautofill@mozilla.org\":\"0f464851-a80d-4b77-aa80-fd9e0809850a\",\"pictureinpicture@mozilla.org\":\"f8c91d47-f0ef-4640-939f-fdacdb3d133b\",\"screenshots@mozilla.org\":\"aef70bdf-b977-42fe-8c2c-5bb5a9f27988\",\"webcompat-reporter@mozilla.org\":\"6cc4f7d1-0073-4e83-a6bc-c94a501627e4\",\"webcompat@mozilla.org\":\"998f8075-5a62-4b93-bc36-8eaab2446be4\",\"default-theme@mozilla.org\":\"cc4ec545-b3d8-4250-b0b0-c5c0a2b733d3\",\"google@search.mozilla.org\":\"bb5e0066-24aa-499f-8488-649135e38e16\",\"leo_ende_de@search.mozilla.org\":\"b9750f8e-96cf-415c-b092-ca62983bfb95\",\"ecosia@search.mozilla.org\":\"30f1951b-9483-4e17-a8a7-948aae81c9b2\",\"wikipedia@search.mozilla.org\":\"f9cb6e9e-e94d-478e-9df7-072889d0cfff\",\"bing@search.mozilla.org\":\"d9bf976a-c77b-46a9-9c15-c09ebb90b4da\",\"ddg@search.mozilla.org\":\"ccbadbe8-202e-4494-a0bd-30abdd0d71b4\",\"ebay@search.mozilla.org\":\"cc87b04c-b64e-4eaf-941b-985bca1deeef\",\"amazon@search.mozilla.org\":\"0d2805c3-96b4-4b57-89a0-afab3ac31b86\",\"uBlock0@raymondhill.net\":\"9de8192c-2f47-40a5-b77f-eb307c7d9c01\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1635970098);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx-shader-check.build-version", "20210927210923");
user_pref("gfx-shader-check.device-id", "0x731f");
user_pref("gfx-shader-check.driver-version", "27.20.22025.1006");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "93.0");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x731f");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "27.20.22025.1006");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0x731f");
user_pref("sanity-test.driver-version", "27.20.22025.1006");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20210927210923");
user_pref("security.sandbox.content.tempDirSuffix", "{d5a91dda-179d-49bf-85b1-d3fc174f24c8}");
user_pref("toolkit.startup.last_success", 1635970095);
user_pref("toolkit.telemetry.cachedClientID", "2719fe81-dc4c-4810-a4ca-7c1866dbe78d");
user_pref("toolkit.telemetry.previousBuildID", "20210927210923");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
